version: "3.5"
services: 
  db:
    image: postgres:9.6
    ports:
      - "54320:5432"
    volumes:
      - ./docker/volumes/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_PORT=5432
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    links:
      - db
    depends_on:
      - "db"
